/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Connection.xs. Do not edit this file, edit Connection.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Connection.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Connection.c"

XS(XS_Purple__Connection_get_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_get_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::get_account", "gc");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	Purple__Account	RETVAL;

	RETVAL = purple_connection_get_account(gc);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Account");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Connection_get_password); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_get_password)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::get_password", "gc");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_connection_get_password(gc);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Connection_get_display_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_get_display_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::get_display_name", "gc");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_connection_get_display_name(gc);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Connection_notice); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_notice)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::notice", "gc, text");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	const char *	text = (const char *)SvPV_nolen(ST(1));

	purple_connection_notice(gc, text);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Connection_error); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_error)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::error", "gc, reason");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	const char *	reason = (const char *)SvPV_nolen(ST(1));

	purple_connection_error(gc, reason);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Connection_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::destroy", "gc");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));

	purple_connection_destroy(gc);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Connection_set_state); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_set_state)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::set_state", "gc, state");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	Purple__ConnectionState	state = (Purple__ConnectionState)SvIV(ST(1));

	purple_connection_set_state(gc, state);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Connection_set_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_set_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::set_account", "gc, account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));

	purple_connection_set_account(gc, account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Connection_set_display_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_set_display_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::set_display_name", "gc, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	purple_connection_set_display_name(gc, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Connection_get_state); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connection_get_state)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connection::get_state", "gc");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	Purple__ConnectionState	RETVAL;
	dXSTARG;

	RETVAL = purple_connection_get_state(gc);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Connections_disconnect_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connections_disconnect_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connections::disconnect_all", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_connections_disconnect_all();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Connections_get_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connections_get_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connections::get_all", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 75 "Connection.xs"
	GList *l;
#line 272 "Connection.c"
#line 77 "Connection.xs"
	for (l = purple_connections_get_all(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Connection")));
	}
#line 277 "Connection.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Connections_get_connecting); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connections_get_connecting)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connections::get_connecting", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 84 "Connection.xs"
	GList *l;
#line 300 "Connection.c"
#line 86 "Connection.xs"
	for (l = purple_connections_get_connecting(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Connection")));
	}
#line 305 "Connection.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Connections_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Connections_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Connections::get_handle", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_connections_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Connection); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Connection)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Connection::get_account", XS_Purple__Connection_get_account, file, "$");
        newXSproto("Purple::Connection::get_password", XS_Purple__Connection_get_password, file, "$");
        newXSproto("Purple::Connection::get_display_name", XS_Purple__Connection_get_display_name, file, "$");
        newXSproto("Purple::Connection::notice", XS_Purple__Connection_notice, file, "$$");
        newXSproto("Purple::Connection::error", XS_Purple__Connection_error, file, "$$");
        newXSproto("Purple::Connection::destroy", XS_Purple__Connection_destroy, file, "$");
        newXSproto("Purple::Connection::set_state", XS_Purple__Connection_set_state, file, "$$");
        newXSproto("Purple::Connection::set_account", XS_Purple__Connection_set_account, file, "$$");
        newXSproto("Purple::Connection::set_display_name", XS_Purple__Connection_set_display_name, file, "$$");
        newXSproto("Purple::Connection::get_state", XS_Purple__Connection_get_state, file, "$");
        newXSproto("Purple::Connections::disconnect_all", XS_Purple__Connections_disconnect_all, file, "");
        newXSproto("Purple::Connections::get_all", XS_Purple__Connections_get_all, file, "");
        newXSproto("Purple::Connections::get_connecting", XS_Purple__Connections_get_connecting, file, "");
        newXSproto("Purple::Connections::get_handle", XS_Purple__Connections_get_handle, file, "");

    /* Initialisation Section */

#line 7 "Connection.xs"
{
	HV *stash = gv_stashpv("Purple::Connection::State", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_##name}
		const_iv(DISCONNECTED),
		const_iv(CONNECTED),
		const_iv(CONNECTING),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 383 "Connection.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

