/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Plugin.xs. Do not edit this file, edit Plugin.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Plugin.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Plugin.c"

XS(XS_Purple__Plugin_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::new", "native, path");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	gboolean	native = (bool)SvTRUE(ST(0));
	const char *	path = (const char *)SvPV_nolen(ST(1));
	Purple__Plugin	RETVAL;

	RETVAL = purple_plugin_new(native, path);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Plugin");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_probe); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_probe)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::probe", "filename");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	filename = (const char *)SvPV_nolen(ST(0));
	Purple__Plugin	RETVAL;

	RETVAL = purple_plugin_probe(filename);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Plugin");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_register); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_register)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::register", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_plugin_register(plugin);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_load); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_load)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::load", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_plugin_load(plugin);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_unload); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_unload)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::unload", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_plugin_unload(plugin);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_reload); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_reload)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::reload", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_plugin_reload(plugin);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::destroy", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));

	purple_plugin_destroy(plugin);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugin_is_loaded); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_is_loaded)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::is_loaded", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_plugin_is_loaded(plugin);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_is_unloadable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_is_unloadable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::is_unloadable", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_plugin_is_unloadable(plugin);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_get_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_get_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::get_id", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const gchar *	RETVAL;
	dXSTARG;

	RETVAL = purple_plugin_get_id(plugin);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::get_name", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const gchar *	RETVAL;
	dXSTARG;

	RETVAL = purple_plugin_get_name(plugin);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_get_version); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_get_version)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::get_version", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const gchar *	RETVAL;
	dXSTARG;

	RETVAL = purple_plugin_get_version(plugin);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_get_summary); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_get_summary)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::get_summary", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const gchar *	RETVAL;
	dXSTARG;

	RETVAL = purple_plugin_get_summary(plugin);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_get_description); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_get_description)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::get_description", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const gchar *	RETVAL;
	dXSTARG;

	RETVAL = purple_plugin_get_description(plugin);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_get_author); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_get_author)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::get_author", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const gchar *	RETVAL;
	dXSTARG;

	RETVAL = purple_plugin_get_author(plugin);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin_get_homepage); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin_get_homepage)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::get_homepage", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const gchar *	RETVAL;
	dXSTARG;

	RETVAL = purple_plugin_get_homepage(plugin);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugin__IPC_unregister); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin__IPC_unregister)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::IPC::unregister", "plugin, command");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));
	const char *	command = (const char *)SvPV_nolen(ST(1));

	purple_plugin_ipc_unregister(plugin, command);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugin__IPC_unregister_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugin__IPC_unregister_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugin::IPC::unregister_all", "plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Plugin	plugin = purple_perl_ref_object(ST(0));

	purple_plugin_ipc_unregister_all(plugin);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugins_add_search_path); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_add_search_path)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::add_search_path", "path");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	path = (const char *)SvPV_nolen(ST(0));

	purple_plugins_add_search_path(path);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugins_unload_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_unload_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::unload_all", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_plugins_unload_all();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugins_destroy_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_destroy_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::destroy_all", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_plugins_destroy_all();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugins_load_saved); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_load_saved)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::load_saved", "key");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	key = (const char *)SvPV_nolen(ST(0));

	purple_plugins_load_saved(key);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugins_probe); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_probe)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::probe", "ext");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	ext = (const char *)SvPV_nolen(ST(0));

	purple_plugins_probe(ext);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Plugins_enabled); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_enabled)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::enabled", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	gboolean	RETVAL;

	RETVAL = purple_plugins_enabled();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugins_find_with_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_find_with_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::find_with_name", "name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	name = (const char *)SvPV_nolen(ST(0));
	Purple__Plugin	RETVAL;

	RETVAL = purple_plugins_find_with_name(name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Plugin");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugins_find_with_filename); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_find_with_filename)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::find_with_filename", "filename");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	filename = (const char *)SvPV_nolen(ST(0));
	Purple__Plugin	RETVAL;

	RETVAL = purple_plugins_find_with_filename(filename);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Plugin");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugins_find_with_basename); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_find_with_basename)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::find_with_basename", "basename");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	basename = (const char *)SvPV_nolen(ST(0));
	Purple__Plugin	RETVAL;

	RETVAL = purple_plugins_find_with_basename(basename);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Plugin");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugins_find_with_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_find_with_id)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::find_with_id", "id");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	id = (const char *)SvPV_nolen(ST(0));
	Purple__Plugin	RETVAL;

	RETVAL = purple_plugins_find_with_id(id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Plugin");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Plugins_get_loaded); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_get_loaded)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::get_loaded", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 141 "Plugin.xs"
	GList *l;
#line 660 "Plugin.c"
#line 143 "Plugin.xs"
	for (l = purple_plugins_get_loaded(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Plugin")));
	}
#line 665 "Plugin.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Plugins_get_protocols); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_get_protocols)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::get_protocols", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 150 "Plugin.xs"
	GList *l;
#line 688 "Plugin.c"
#line 152 "Plugin.xs"
	for (l = purple_plugins_get_protocols(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Plugin")));
	}
#line 693 "Plugin.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Plugins_get_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_get_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::get_all", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 159 "Plugin.xs"
	GList *l;
#line 716 "Plugin.c"
#line 161 "Plugin.xs"
	for (l = purple_plugins_get_all(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Plugin")));
	}
#line 721 "Plugin.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Plugins_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Plugins_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Plugins::get_handle", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_plugins_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Plugin); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Plugin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Plugin::new", XS_Purple__Plugin_new, file, "$$");
        newXSproto("Purple::Plugin::probe", XS_Purple__Plugin_probe, file, "$");
        newXSproto("Purple::Plugin::register", XS_Purple__Plugin_register, file, "$");
        newXSproto("Purple::Plugin::load", XS_Purple__Plugin_load, file, "$");
        newXSproto("Purple::Plugin::unload", XS_Purple__Plugin_unload, file, "$");
        newXSproto("Purple::Plugin::reload", XS_Purple__Plugin_reload, file, "$");
        newXSproto("Purple::Plugin::destroy", XS_Purple__Plugin_destroy, file, "$");
        newXSproto("Purple::Plugin::is_loaded", XS_Purple__Plugin_is_loaded, file, "$");
        newXSproto("Purple::Plugin::is_unloadable", XS_Purple__Plugin_is_unloadable, file, "$");
        newXSproto("Purple::Plugin::get_id", XS_Purple__Plugin_get_id, file, "$");
        newXSproto("Purple::Plugin::get_name", XS_Purple__Plugin_get_name, file, "$");
        newXSproto("Purple::Plugin::get_version", XS_Purple__Plugin_get_version, file, "$");
        newXSproto("Purple::Plugin::get_summary", XS_Purple__Plugin_get_summary, file, "$");
        newXSproto("Purple::Plugin::get_description", XS_Purple__Plugin_get_description, file, "$");
        newXSproto("Purple::Plugin::get_author", XS_Purple__Plugin_get_author, file, "$");
        newXSproto("Purple::Plugin::get_homepage", XS_Purple__Plugin_get_homepage, file, "$");
        newXSproto("Purple::Plugin::IPC::unregister", XS_Purple__Plugin__IPC_unregister, file, "$$");
        newXSproto("Purple::Plugin::IPC::unregister_all", XS_Purple__Plugin__IPC_unregister_all, file, "$");
        newXSproto("Purple::Plugins::add_search_path", XS_Purple__Plugins_add_search_path, file, "$");
        newXSproto("Purple::Plugins::unload_all", XS_Purple__Plugins_unload_all, file, "");
        newXSproto("Purple::Plugins::destroy_all", XS_Purple__Plugins_destroy_all, file, "");
        newXSproto("Purple::Plugins::load_saved", XS_Purple__Plugins_load_saved, file, "$");
        newXSproto("Purple::Plugins::probe", XS_Purple__Plugins_probe, file, "$");
        newXSproto("Purple::Plugins::enabled", XS_Purple__Plugins_enabled, file, "");
        newXSproto("Purple::Plugins::find_with_name", XS_Purple__Plugins_find_with_name, file, "$");
        newXSproto("Purple::Plugins::find_with_filename", XS_Purple__Plugins_find_with_filename, file, "$");
        newXSproto("Purple::Plugins::find_with_basename", XS_Purple__Plugins_find_with_basename, file, "$");
        newXSproto("Purple::Plugins::find_with_id", XS_Purple__Plugins_find_with_id, file, "$");
        newXSproto("Purple::Plugins::get_loaded", XS_Purple__Plugins_get_loaded, file, "");
        newXSproto("Purple::Plugins::get_protocols", XS_Purple__Plugins_get_protocols, file, "");
        newXSproto("Purple::Plugins::get_all", XS_Purple__Plugins_get_all, file, "");
        newXSproto("Purple::Plugins::get_handle", XS_Purple__Plugins_get_handle, file, "");

    /* Initialisation Section */

#line 7 "Plugin.xs"
{
	HV *stash = gv_stashpv("Purple::Plugin::Type", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_PLUGIN_##name}
		const_iv(UNKNOWN),
		const_iv(STANDARD),
		const_iv(LOADER),
		const_iv(PROTOCOL),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 818 "Plugin.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

