/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Privacy.xs. Do not edit this file, edit Privacy.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Privacy.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Privacy.c"

XS(XS_Purple__Privacy_permit_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Privacy_permit_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Privacy::permit_add", "account, name, local_only");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	gboolean	local_only = (bool)SvTRUE(ST(2));
	gboolean	RETVAL;

	RETVAL = purple_privacy_permit_add(account, name, local_only);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Privacy_permit_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Privacy_permit_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Privacy::permit_remove", "account, name, local_only");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	gboolean	local_only = (bool)SvTRUE(ST(2));
	gboolean	RETVAL;

	RETVAL = purple_privacy_permit_remove(account, name, local_only);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Privacy_deny_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Privacy_deny_add)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Privacy::deny_add", "account, name, local_only");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	gboolean	local_only = (bool)SvTRUE(ST(2));
	gboolean	RETVAL;

	RETVAL = purple_privacy_deny_add(account, name, local_only);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Privacy_deny_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Privacy_deny_remove)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Privacy::deny_remove", "account, name, local_only");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	gboolean	local_only = (bool)SvTRUE(ST(2));
	gboolean	RETVAL;

	RETVAL = purple_privacy_deny_remove(account, name, local_only);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Privacy_check); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Privacy_check)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Privacy::check", "account, who");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	who = (const char *)SvPV_nolen(ST(1));
	gboolean	RETVAL;

	RETVAL = purple_privacy_check(account, who);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Privacy); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Privacy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Privacy::permit_add", XS_Purple__Privacy_permit_add, file, "$$$");
        newXSproto("Purple::Privacy::permit_remove", XS_Purple__Privacy_permit_remove, file, "$$$");
        newXSproto("Purple::Privacy::deny_add", XS_Purple__Privacy_deny_add, file, "$$$");
        newXSproto("Purple::Privacy::deny_remove", XS_Purple__Privacy_deny_remove, file, "$$$");
        newXSproto("Purple::Privacy::check", XS_Purple__Privacy_check, file, "$$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

