/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Prpl.xs. Do not edit this file, edit Prpl.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Prpl.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Prpl.c"

XS(XS_Purple__Find_prpl); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Find_prpl)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Find::prpl", "id");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	id = (const char *)SvPV_nolen(ST(0));
	Purple__Plugin	RETVAL;

	RETVAL = purple_find_prpl(id);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Plugin");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Prpl_change_account_status); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Prpl_change_account_status)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Prpl::change_account_status", "account, old_status, new_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	Purple__Status	old_status = purple_perl_ref_object(ST(1));
	Purple__Status	new_status = purple_perl_ref_object(ST(2));

	purple_prpl_change_account_status(account, old_status, new_status);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Prpl_get_statuses); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Prpl_get_statuses)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Prpl::get_statuses", "account, presence");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	Purple__Presence	presence = purple_perl_ref_object(ST(1));
#line 24 "Prpl.xs"
	GList *l, *ll;
#line 83 "Prpl.c"
#line 26 "Prpl.xs"
	ll = purple_prpl_get_statuses(account,presence);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Status")));
	}
	/* We can free the list here but the script needs to free the
	 * Purple::Status 'objects' itself. */
	g_list_free(ll);
#line 92 "Prpl.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Prpl_got_account_idle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Prpl_got_account_idle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Prpl::got_account_idle", "account, idle, idle_time");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	gboolean	idle = (bool)SvTRUE(ST(1));
	time_t	idle_time = (time_t)SvIV(ST(2));

	purple_prpl_got_account_idle(account, idle, idle_time);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Prpl_got_account_login_time); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Prpl_got_account_login_time)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Prpl::got_account_login_time", "account, login_time");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	time_t	login_time = (time_t)SvIV(ST(1));

	purple_prpl_got_account_login_time(account, login_time);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Prpl_got_user_idle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Prpl_got_user_idle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Prpl::got_user_idle", "account, name, idle, idle_time");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	gboolean	idle = (bool)SvTRUE(ST(2));
	time_t	idle_time = (time_t)SvIV(ST(3));

	purple_prpl_got_user_idle(account, name, idle, idle_time);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Prpl_got_user_login_time); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Prpl_got_user_login_time)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Prpl::got_user_login_time", "account, name, login_time");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	time_t	login_time = (time_t)SvIV(ST(2));

	purple_prpl_got_user_login_time(account, name, login_time);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Prpl_send_raw); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Prpl_send_raw)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Prpl::send_raw", "gc, str");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Connection	gc = purple_perl_ref_object(ST(0));
	const char *	str = (const char *)SvPV_nolen(ST(1));
#line 63 "Prpl.xs"
	PurplePluginProtocolInfo *prpl_info;
#line 203 "Prpl.c"
	int	RETVAL;
	dXSTARG;
#line 65 "Prpl.xs"
	if (!gc)
		RETVAL = 0;
	else {
		prpl_info = PURPLE_PLUGIN_PROTOCOL_INFO(gc->prpl);
		if (prpl_info && prpl_info->send_raw != NULL) {
			RETVAL = prpl_info->send_raw(gc, str, strlen(str));
		} else {
			RETVAL = 0;
		}
	}
#line 217 "Prpl.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Prpl); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Prpl)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Find::prpl", XS_Purple__Find_prpl, file, "$");
        newXSproto("Purple::Prpl::change_account_status", XS_Purple__Prpl_change_account_status, file, "$$$");
        newXSproto("Purple::Prpl::get_statuses", XS_Purple__Prpl_get_statuses, file, "$$");
        newXSproto("Purple::Prpl::got_account_idle", XS_Purple__Prpl_got_account_idle, file, "$$$");
        newXSproto("Purple::Prpl::got_account_login_time", XS_Purple__Prpl_got_account_login_time, file, "$$");
        newXSproto("Purple::Prpl::got_user_idle", XS_Purple__Prpl_got_user_idle, file, "$$$$");
        newXSproto("Purple::Prpl::got_user_login_time", XS_Purple__Prpl_got_user_login_time, file, "$$$");
        newXSproto("Purple::Prpl::send_raw", XS_Purple__Prpl_send_raw, file, "$$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

