/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of SavedStatuses.xs. Do not edit this file, edit SavedStatuses.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "SavedStatuses.xs"
#include "module.h"

/* I can't get this to work, both with and without the const on the return
 * type I get errors from gcc. One way about ignoring types in a cast, and the
 * other about assigning to read-only variables.
const Purple::StatusType
purple_savedstatus_substatus_get_type(substatus)
	const Purple::SavedStatus::Sub substatus
*/

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 25 "SavedStatuses.c"

XS(XS_Purple__SavedStatus_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::new", "title, type");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	title = (const char *)SvPV_nolen(ST(0));
	Purple__StatusPrimitive	type = (Purple__StatusPrimitive)SvIV(ST(1));
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_new(title, type);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_set_title); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_set_title)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::set_title", "status, title");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	status = purple_perl_ref_object(ST(0));
	const char *	title = (const char *)SvPV_nolen(ST(1));

	purple_savedstatus_set_title(status, title);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus_set_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_set_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::set_type", "status, type");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	status = purple_perl_ref_object(ST(0));
	Purple__StatusPrimitive	type = (Purple__StatusPrimitive)SvIV(ST(1));

	purple_savedstatus_set_type(status, type);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus_set_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_set_message)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::set_message", "status, message");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	status = purple_perl_ref_object(ST(0));
	const char *	message = (const char *)SvPV_nolen(ST(1));

	purple_savedstatus_set_message(status, message);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus_set_substatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_set_substatus)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::set_substatus", "status, account, type, message");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	status = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));
	Purple__StatusType	type = purple_perl_ref_object(ST(2));
	const char *	message = (const char *)SvPV_nolen(ST(3));

	purple_savedstatus_set_substatus(status, account, type, message);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus_unset_substatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_unset_substatus)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::unset_substatus", "status, account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	status = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));

	purple_savedstatus_unset_substatus(status, account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus_delete); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_delete)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::delete", "title");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	title = (const char *)SvPV_nolen(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_savedstatus_delete(title);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_current); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_current)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_current", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_get_current();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_default); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_default)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_default", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_get_default();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_idleaway); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_idleaway)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_idleaway", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_get_idleaway();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_is_idleaway); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_is_idleaway)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::is_idleaway", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	gboolean	RETVAL;

	RETVAL = purple_savedstatus_is_idleaway();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_set_idleaway); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_set_idleaway)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::set_idleaway", "idleaway");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	gboolean	idleaway = (bool)SvTRUE(ST(0));

	purple_savedstatus_set_idleaway(idleaway);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus_get_startup); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_startup)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_startup", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_get_startup();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_find)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::find", "title");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	title = (const char *)SvPV_nolen(ST(0));
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_find(title);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_find_by_creation_time); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_find_by_creation_time)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::find_by_creation_time", "creation_time");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	time_t	creation_time = (time_t)SvIV(ST(0));
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_find_by_creation_time(creation_time);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_find_transient_by_type_and_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_find_transient_by_type_and_message)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::find_transient_by_type_and_message", "type, message");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__StatusPrimitive	type = (Purple__StatusPrimitive)SvIV(ST(0));
	const char *	message = (const char *)SvPV_nolen(ST(1));
	Purple__SavedStatus	RETVAL;

	RETVAL = purple_savedstatus_find_transient_by_type_and_message(type, message);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_is_transient); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_is_transient)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::is_transient", "saved_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_savedstatus_is_transient(saved_status);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_title); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_title)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_title", "saved_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_savedstatus_get_title(saved_status);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_type", "saved_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	Purple__StatusPrimitive	RETVAL;
	dXSTARG;

	RETVAL = purple_savedstatus_get_type(saved_status);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_message)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_message", "saved_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_savedstatus_get_message(saved_status);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_creation_time); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_creation_time)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_creation_time", "saved_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	time_t	RETVAL;
	dXSTARG;

	RETVAL = purple_savedstatus_get_creation_time(saved_status);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_has_substatuses); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_has_substatuses)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::has_substatuses", "saved_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_savedstatus_has_substatuses(saved_status);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_get_substatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_get_substatus)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::get_substatus", "saved_status, account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));
	Purple__SavedStatus__Sub	RETVAL;

	RETVAL = purple_savedstatus_get_substatus(saved_status, account);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::SavedStatus::Sub");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatus_activate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_activate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::activate", "saved_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));

	purple_savedstatus_activate(saved_status);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus_activate_for_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus_activate_for_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::activate_for_account", "saved_status, account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus	saved_status = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));

	purple_savedstatus_activate_for_account(saved_status, account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__SavedStatus__Sub_get_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatus__Sub_get_message)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatus::Sub::get_message", "substatus");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const Purple__SavedStatus__Sub	substatus = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_savedstatus_substatus_get_message(substatus);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__SavedStatuses_get_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatuses_get_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatuses::get_all", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 133 "SavedStatuses.xs"
	GList *l;
#line 632 "SavedStatuses.c"
#line 135 "SavedStatuses.xs"
	for (l = purple_savedstatuses_get_all(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::SavedStatus")));
	}
#line 637 "SavedStatuses.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__SavedStatuses_get_popular); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatuses_get_popular)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatuses::get_popular", "how_many");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	unsigned int	how_many = (unsigned int)SvUV(ST(0));
#line 143 "SavedStatuses.xs"
	GList *l, *ll;
#line 661 "SavedStatuses.c"
#line 145 "SavedStatuses.xs"
	ll = purple_savedstatuses_get_popular(how_many);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::SavedStatus")));
	}
	g_list_free(ll);
#line 668 "SavedStatuses.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__SavedStatuses_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__SavedStatuses_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::SavedStatuses::get_handle", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_savedstatuses_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__SavedStatus); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__SavedStatus)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::SavedStatus::new", XS_Purple__SavedStatus_new, file, "$$");
        newXSproto("Purple::SavedStatus::set_title", XS_Purple__SavedStatus_set_title, file, "$$");
        newXSproto("Purple::SavedStatus::set_type", XS_Purple__SavedStatus_set_type, file, "$$");
        newXSproto("Purple::SavedStatus::set_message", XS_Purple__SavedStatus_set_message, file, "$$");
        newXSproto("Purple::SavedStatus::set_substatus", XS_Purple__SavedStatus_set_substatus, file, "$$$$");
        newXSproto("Purple::SavedStatus::unset_substatus", XS_Purple__SavedStatus_unset_substatus, file, "$$");
        newXSproto("Purple::SavedStatus::delete", XS_Purple__SavedStatus_delete, file, "$");
        newXSproto("Purple::SavedStatus::get_current", XS_Purple__SavedStatus_get_current, file, "");
        newXSproto("Purple::SavedStatus::get_default", XS_Purple__SavedStatus_get_default, file, "");
        newXSproto("Purple::SavedStatus::get_idleaway", XS_Purple__SavedStatus_get_idleaway, file, "");
        newXSproto("Purple::SavedStatus::is_idleaway", XS_Purple__SavedStatus_is_idleaway, file, "");
        newXSproto("Purple::SavedStatus::set_idleaway", XS_Purple__SavedStatus_set_idleaway, file, "$");
        newXSproto("Purple::SavedStatus::get_startup", XS_Purple__SavedStatus_get_startup, file, "");
        newXSproto("Purple::SavedStatus::find", XS_Purple__SavedStatus_find, file, "$");
        newXSproto("Purple::SavedStatus::find_by_creation_time", XS_Purple__SavedStatus_find_by_creation_time, file, "$");
        newXSproto("Purple::SavedStatus::find_transient_by_type_and_message", XS_Purple__SavedStatus_find_transient_by_type_and_message, file, "$$");
        newXSproto("Purple::SavedStatus::is_transient", XS_Purple__SavedStatus_is_transient, file, "$");
        newXSproto("Purple::SavedStatus::get_title", XS_Purple__SavedStatus_get_title, file, "$");
        newXSproto("Purple::SavedStatus::get_type", XS_Purple__SavedStatus_get_type, file, "$");
        newXSproto("Purple::SavedStatus::get_message", XS_Purple__SavedStatus_get_message, file, "$");
        newXSproto("Purple::SavedStatus::get_creation_time", XS_Purple__SavedStatus_get_creation_time, file, "$");
        newXSproto("Purple::SavedStatus::has_substatuses", XS_Purple__SavedStatus_has_substatuses, file, "$");
        newXSproto("Purple::SavedStatus::get_substatus", XS_Purple__SavedStatus_get_substatus, file, "$$");
        newXSproto("Purple::SavedStatus::activate", XS_Purple__SavedStatus_activate, file, "$");
        newXSproto("Purple::SavedStatus::activate_for_account", XS_Purple__SavedStatus_activate_for_account, file, "$$");
        newXSproto("Purple::SavedStatus::Sub::get_message", XS_Purple__SavedStatus__Sub_get_message, file, "$");
        newXSproto("Purple::SavedStatuses::get_all", XS_Purple__SavedStatuses_get_all, file, "");
        newXSproto("Purple::SavedStatuses::get_popular", XS_Purple__SavedStatuses_get_popular, file, "$");
        newXSproto("Purple::SavedStatuses::get_handle", XS_Purple__SavedStatuses_get_handle, file, "");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

