/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of XMLNode.xs. Do not edit this file, edit XMLNode.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "XMLNode.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "XMLNode.c"

XS(XS_Purple__XMLNode_copy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_copy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::copy", "src");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	src = purple_perl_ref_object(ST(0));
	Purple__XMLNode	RETVAL;

	RETVAL = xmlnode_copy(src);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_free); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_free)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::free", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));

	xmlnode_free(node);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__XMLNode_from_str); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_from_str)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::from_str", "str");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	RETVAL;
	STRLEN	STRLEN_length_of_str;
	gssize	XSauto_length_of_str;
	const char *	str = (const char *)SvPV(ST(0), STRLEN_length_of_str);

	XSauto_length_of_str = STRLEN_length_of_str;
	RETVAL = xmlnode_from_str(str, XSauto_length_of_str);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::get_name", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;
#line 22 "XMLNode.xs"
	RETVAL = node->name;
#line 107 "XMLNode.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_get_attrib); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_get_attrib)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::get_attrib", "node, attr");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	const char *	attr = (const char *)SvPV_nolen(ST(1));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = xmlnode_get_attrib(node, attr);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_get_child); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_get_child)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::get_child", "parent, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	parent = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
#line 36 "XMLNode.xs"
	xmlnode *tmp;
#line 154 "XMLNode.c"
	Purple__XMLNode	RETVAL;
#line 38 "XMLNode.xs"
	if (!name || *name == '\0') {
		tmp = parent->child;
		while (tmp && tmp->type != XMLNODE_TYPE_TAG)
			tmp = tmp->next;
		RETVAL = tmp;
	} else
		RETVAL = xmlnode_get_child(parent, name);
#line 164 "XMLNode.c"
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_get_child_with_namespace); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_get_child_with_namespace)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::get_child_with_namespace", "parent, name, xmlns");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	parent = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	const char *	xmlns = (const char *)SvPV_nolen(ST(2));
	Purple__XMLNode	RETVAL;

	RETVAL = xmlnode_get_child_with_namespace(parent, name, xmlns);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_get_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_get_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::get_data", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	gchar_own *	RETVAL;

	RETVAL = xmlnode_get_data(node);
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);

    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_get_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_get_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::get_next", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
#line 62 "XMLNode.xs"
	xmlnode *tmp;
#line 243 "XMLNode.c"
	Purple__XMLNode	RETVAL;
#line 64 "XMLNode.xs"
	tmp = node->next;
	while (tmp && tmp->type != XMLNODE_TYPE_TAG)
		tmp = tmp->next;
	RETVAL = tmp;
#line 250 "XMLNode.c"
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_get_next_twin); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_get_next_twin)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::get_next_twin", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	Purple__XMLNode	RETVAL;

	RETVAL = xmlnode_get_next_twin(node);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_insert_child); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_insert_child)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::insert_child", "parent, child");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	parent = purple_perl_ref_object(ST(0));
	Purple__XMLNode	child = purple_perl_ref_object(ST(1));

	xmlnode_insert_child(parent, child);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__XMLNode_insert_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_insert_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::insert_data", "node, data, size");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	const char *	data = (const char *)SvPV_nolen(ST(1));
	gssize	size = (gssize)SvIV(ST(2));

	xmlnode_insert_data(node, data, size);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__XMLNode_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::new", "class, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	name = (const char *)SvPV_nolen(ST(1));
	Purple__XMLNode	RETVAL;

	RETVAL = xmlnode_new(name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_new_child); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_new_child)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::new_child", "parent, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	parent = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	Purple__XMLNode	RETVAL;

	RETVAL = xmlnode_new_child(parent, name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::XMLNode");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_remove_attrib); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_remove_attrib)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::remove_attrib", "node, attr");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	const char *	attr = (const char *)SvPV_nolen(ST(1));

	xmlnode_remove_attrib(node, attr);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__XMLNode_set_attrib); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_set_attrib)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::set_attrib", "node, attr, value");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	const char *	attr = (const char *)SvPV_nolen(ST(1));
	const char *	value = (const char *)SvPV_nolen(ST(2));

	xmlnode_set_attrib(node, attr, value);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__XMLNode_to_formatted_str); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_to_formatted_str)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::to_formatted_str", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	gchar_own *	RETVAL;
#line 112 "XMLNode.xs"
	RETVAL = xmlnode_to_formatted_str(node, NULL);
#line 434 "XMLNode.c"
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);

    }
    XSRETURN(1);
}


XS(XS_Purple__XMLNode_to_str); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__XMLNode_to_str)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::XMLNode::to_str", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__XMLNode	node = purple_perl_ref_object(ST(0));
	gchar_own *	RETVAL;
#line 120 "XMLNode.xs"
	RETVAL = xmlnode_to_str(node, NULL);
#line 464 "XMLNode.c"
	ST(0) = sv_newmortal();
	/* used when we can directly own the returned string. */
	/* we have to copy in the case when perl's malloc != gtk's malloc,
	 * so best copy all the time. */
	sv_setpv ((SV*)ST(0), RETVAL);
	SvUTF8_on (ST(0));
	g_free (RETVAL);

    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__XMLNode); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__XMLNode)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::XMLNode::copy", XS_Purple__XMLNode_copy, file, "$");
        newXSproto("Purple::XMLNode::free", XS_Purple__XMLNode_free, file, "$");
        newXSproto("Purple::XMLNode::from_str", XS_Purple__XMLNode_from_str, file, "$");
        newXSproto("Purple::XMLNode::get_name", XS_Purple__XMLNode_get_name, file, "$");
        newXSproto("Purple::XMLNode::get_attrib", XS_Purple__XMLNode_get_attrib, file, "$$");
        newXSproto("Purple::XMLNode::get_child", XS_Purple__XMLNode_get_child, file, "$$");
        newXSproto("Purple::XMLNode::get_child_with_namespace", XS_Purple__XMLNode_get_child_with_namespace, file, "$$$");
        newXSproto("Purple::XMLNode::get_data", XS_Purple__XMLNode_get_data, file, "$");
        newXSproto("Purple::XMLNode::get_next", XS_Purple__XMLNode_get_next, file, "$");
        newXSproto("Purple::XMLNode::get_next_twin", XS_Purple__XMLNode_get_next_twin, file, "$");
        newXSproto("Purple::XMLNode::insert_child", XS_Purple__XMLNode_insert_child, file, "$$");
        newXSproto("Purple::XMLNode::insert_data", XS_Purple__XMLNode_insert_data, file, "$$$");
        newXSproto("Purple::XMLNode::new", XS_Purple__XMLNode_new, file, "$$");
        newXSproto("Purple::XMLNode::new_child", XS_Purple__XMLNode_new_child, file, "$$");
        newXSproto("Purple::XMLNode::remove_attrib", XS_Purple__XMLNode_remove_attrib, file, "$$");
        newXSproto("Purple::XMLNode::set_attrib", XS_Purple__XMLNode_set_attrib, file, "$$$");
        newXSproto("Purple::XMLNode::to_formatted_str", XS_Purple__XMLNode_to_formatted_str, file, "$");
        newXSproto("Purple::XMLNode::to_str", XS_Purple__XMLNode_to_str, file, "$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

