/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of BuddyList.xs. Do not edit this file, edit BuddyList.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "BuddyList.xs"
#undef PURPLE_DISABLE_DEPRECATED
#include "module.h"
#include "../perl-handlers.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 19 "BuddyList.c"

XS(XS_Purple_get_blist); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple_get_blist)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::get_blist", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList	RETVAL;

	RETVAL = purple_get_blist();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple_set_blist); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple_set_blist)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::set_blist", "blist");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList	blist = purple_perl_ref_object(ST(0));

	purple_set_blist(blist);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Find_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Find_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Find::buddy", "account, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	Purple__BuddyList__Buddy	RETVAL;

	RETVAL = purple_find_buddy(account, name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Buddy");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Find_buddies); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Find_buddies)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Find::buddies", "account, name");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
#line 48 "BuddyList.xs"
	GSList *l, *ll;
#line 107 "BuddyList.c"
#line 50 "BuddyList.xs"
	ll = purple_find_buddies(account, name);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::BuddyList::Buddy")));
	}
	g_slist_free(ll);
#line 114 "BuddyList.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Find_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Find_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Find::group", "name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	name = (const char *)SvPV_nolen(ST(0));
	Purple__BuddyList__Group	RETVAL;

	RETVAL = purple_find_group(name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Group");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Find_group_on_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Find_group_on_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Find::group_on_account", "group, account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));
	gboolean	RETVAL;

	RETVAL = purple_group_on_account(group, account);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Contact_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Contact_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Contact::new", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	RETVAL;

	RETVAL = purple_contact_new();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Contact");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Contact_get_priority_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Contact_get_priority_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Contact::get_priority_buddy", "contact");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Buddy	RETVAL;

	RETVAL = purple_contact_get_priority_buddy(contact);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Buddy");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Contact_set_alias); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Contact_set_alias)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Contact::set_alias", "contact, alias");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));
	const char *	alias = (const char *)SvPV_nolen(ST(1));

	purple_contact_set_alias(contact, alias);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList__Contact_get_alias); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Contact_get_alias)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Contact::get_alias", "contact");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_contact_get_alias(contact);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Contact_on_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Contact_on_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Contact::on_account", "contact, account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));
	gboolean	RETVAL;

	RETVAL = purple_contact_on_account(contact, account);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Contact_invalidate_priority_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Contact_invalidate_priority_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Contact::invalidate_priority_buddy", "contact");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));

	purple_contact_invalidate_priority_buddy(contact);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList__Group_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Group_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Group::new", "name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	name = (const char *)SvPV_nolen(ST(0));
	Purple__BuddyList__Group	RETVAL;

	RETVAL = purple_group_new(name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Group");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Group_get_accounts); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Group_get_accounts)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Group::get_accounts", "group");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
#line 107 "BuddyList.xs"
	GSList *l, *ll;
#line 345 "BuddyList.c"
#line 109 "BuddyList.xs"
	ll = purple_group_get_accounts(group);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Account")));
	}
	g_slist_free(ll);
#line 352 "BuddyList.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__BuddyList__Group_on_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Group_on_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Group::on_account", "group, account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
	Purple__Account	account = purple_perl_ref_object(ST(1));
	gboolean	RETVAL;

	RETVAL = purple_group_on_account(group, account);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Group_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Group_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Group::get_name", "group");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_group_get_name(group);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList_add_contact); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_add_contact)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::add_contact", "contact, group, node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(1));
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(2));

	purple_blist_add_contact(contact, group, node);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_merge_contact); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_merge_contact)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::merge_contact", "source, node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	source = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(1));

	purple_blist_merge_contact(source, node);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_add_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_add_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::add_group", "group, node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(1));

	purple_blist_add_group(group, node);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_add_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_add_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::add_buddy", "buddy, contact, group, node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(1));
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(2));
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(3));

	purple_blist_add_buddy(buddy, contact, group, node);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_remove_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_remove_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::remove_buddy", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));

	purple_blist_remove_buddy(buddy);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_remove_contact); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_remove_contact)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::remove_contact", "contact");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Contact	contact = purple_perl_ref_object(ST(0));

	purple_blist_remove_contact(contact);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_remove_chat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_remove_chat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::remove_chat", "chat");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Chat	chat = purple_perl_ref_object(ST(0));

	purple_blist_remove_chat(chat);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_remove_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_remove_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::remove_group", "group");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));

	purple_blist_remove_group(group);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_find_chat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_find_chat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::find_chat", "account, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	Purple__BuddyList__Chat	RETVAL;

	RETVAL = purple_blist_find_chat(account, name);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Chat");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList_add_chat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_add_chat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::add_chat", "chat, group, node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Chat	chat = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(1));
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(2));

	purple_blist_add_chat(chat, group, node);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::new", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList	RETVAL;

	RETVAL = purple_blist_new();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList_show); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_show)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::show", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_blist_show();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::destroy", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_blist_destroy();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_set_visible); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_set_visible)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::set_visible", "show");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	gboolean	show = (bool)SvTRUE(ST(0));

	purple_blist_set_visible(show);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_update_buddy_status); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_update_buddy_status)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::update_buddy_status", "buddy, old_status");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__Status	old_status = purple_perl_ref_object(ST(1));

	purple_blist_update_buddy_status(buddy, old_status);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_update_buddy_icon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_update_buddy_icon)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::update_buddy_icon", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));

	purple_blist_update_buddy_icon(buddy);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_rename_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_rename_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::rename_buddy", "buddy, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	purple_blist_rename_buddy(buddy, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_alias_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_alias_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::alias_buddy", "buddy, alias");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	alias = (const char *)SvPV_nolen(ST(1));

	purple_blist_alias_buddy(buddy, alias);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_server_alias_buddy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_server_alias_buddy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::server_alias_buddy", "buddy, alias");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	alias = (const char *)SvPV_nolen(ST(1));

	purple_blist_server_alias_buddy(buddy, alias);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_alias_chat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_alias_chat)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::alias_chat", "chat, alias");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	alias = (const char *)SvPV_nolen(ST(1));

	purple_blist_alias_chat(chat, alias);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_rename_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_rename_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::rename_group", "group, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	purple_blist_rename_group(group, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_add_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_add_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::add_account", "account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));

	purple_blist_add_account(account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_remove_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_remove_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::remove_account", "account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));

	purple_blist_remove_account(account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_get_group_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_get_group_size)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::get_group_size", "group, offline");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
	gboolean	offline = (bool)SvTRUE(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_blist_get_group_size(group, offline);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList_get_group_online_count); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_get_group_online_count)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::get_group_online_count", "group");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Group	group = purple_perl_ref_object(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_blist_get_group_online_count(group);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList_load); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_load)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::load", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_blist_load();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_schedule_save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_schedule_save)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::schedule_save", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_blist_schedule_save();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_request_add_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_request_add_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::request_add_group", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {

	purple_blist_request_add_group();
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::get_handle", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_blist_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList_get_root); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList_get_root)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::get_root", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	RETVAL;

	RETVAL = purple_blist_get_root();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Node");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Node_get_extended_menu); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_get_extended_menu)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::get_extended_menu", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
#line 263 "BuddyList.xs"
	GList *l, *ll;
#line 1054 "BuddyList.c"
#line 265 "BuddyList.xs"
	ll = purple_blist_node_get_extended_menu(node);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Menu::Action")));
	}
	/* We can free the list here but the script needs to free the
	 * Purple::Menu::Action 'objects' itself. */
	g_list_free(ll);
#line 1063 "BuddyList.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__BuddyList__Node_set_bool); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_set_bool)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::set_bool", "node, key, value");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	const char *	key = (const char *)SvPV_nolen(ST(1));
	gboolean	value = (bool)SvTRUE(ST(2));

	purple_blist_node_set_bool(node, key, value);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList__Node_get_bool); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_get_bool)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::get_bool", "node, key");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	const char *	key = (const char *)SvPV_nolen(ST(1));
	gboolean	RETVAL;

	RETVAL = purple_blist_node_get_bool(node, key);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Node_set_int); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_set_int)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::set_int", "node, key, value");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	const char *	key = (const char *)SvPV_nolen(ST(1));
	int	value = (int)SvIV(ST(2));

	purple_blist_node_set_int(node, key, value);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList__Node_get_int); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_get_int)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::get_int", "node, key");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	const char *	key = (const char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = purple_blist_node_get_int(node, key);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Node_get_string); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_get_string)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::get_string", "node, key");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	const char *	key = (const char *)SvPV_nolen(ST(1));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_blist_node_get_string(node, key);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Node_remove_setting); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_remove_setting)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::remove_setting", "node, key");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	const char *	key = (const char *)SvPV_nolen(ST(1));

	purple_blist_node_remove_setting(node, key);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList__Node_set_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_set_flags)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::set_flags", "node, flags");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	Purple__BuddyList__NodeFlags	flags = (Purple__BuddyList__NodeFlags)SvIV(ST(1));

	purple_blist_node_set_flags(node, flags);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList__Node_get_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_get_flags)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::get_flags", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	Purple__BuddyList__NodeFlags	RETVAL;
	dXSTARG;

	RETVAL = purple_blist_node_get_flags(node);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Node_get_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_get_type)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::get_type", "node");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	Purple__BuddyList__NodeType	RETVAL;
	dXSTARG;

	RETVAL = purple_blist_node_get_type(node);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Node_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Node_next)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Node::next", "node, offline");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Node	node = purple_perl_ref_object(ST(0));
	gboolean	offline = (bool)SvTRUE(ST(1));
	Purple__BuddyList__Node	RETVAL;

	RETVAL = purple_blist_node_next(node, offline);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Node");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Chat_get_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Chat_get_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Chat::get_group", "chat");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Chat	chat = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Group	RETVAL;

	RETVAL = purple_chat_get_group(chat);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Group");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Chat_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Chat_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Chat::get_name", "chat");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Chat	chat = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_chat_get_name(chat);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Chat_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Chat_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Chat::new", "account, alias, components");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	alias = (const char *)SvPV_nolen(ST(1));
	SV *	components = ST(2);
	Purple__BuddyList__Chat	RETVAL;
#line 340 "BuddyList.xs"
	HV * t_HV;
	HE * t_HE;
	SV * t_SV;
	GHashTable * t_GHash;
	I32 len;
	char *t_key, *t_value;
#line 1369 "BuddyList.c"
#line 347 "BuddyList.xs"
	t_HV =  (HV *)SvRV(components);
	t_GHash = g_hash_table_new(g_str_hash, g_str_equal);

	for (t_HE = hv_iternext(t_HV); t_HE != NULL; t_HE = hv_iternext(t_HV) ) {
		t_key = hv_iterkey(t_HE, &len);
		t_SV = *hv_fetch(t_HV, t_key, len, 0);
		t_value = SvPVutf8_nolen(t_SV);

		g_hash_table_insert(t_GHash, t_key, t_value);
	}

	RETVAL = purple_chat_new(account, alias, t_GHash);
#line 1383 "BuddyList.c"
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Chat");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::new", "account, name, alias");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));
	const char *	alias = (const char *)SvPV_nolen(ST(2));
	Purple__BuddyList__Buddy	RETVAL;

	RETVAL = purple_buddy_new(account, name, alias);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Buddy");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_server_alias); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_server_alias)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_server_alias", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_buddy_get_server_alias(buddy);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_set_icon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_set_icon)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::set_icon", "buddy, icon");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__Buddy__Icon	icon = purple_perl_ref_object(ST(1));

	purple_buddy_set_icon(buddy, icon);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__BuddyList__Buddy_get_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_account", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__Account	RETVAL;

	RETVAL = purple_buddy_get_account(buddy);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Account");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_group); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_group)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_group", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Group	RETVAL;

	RETVAL = purple_buddy_get_group(buddy);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Group");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_name)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_name", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_buddy_get_name(buddy);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_icon); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_icon)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_icon", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__Buddy__Icon	RETVAL;

	RETVAL = purple_buddy_get_icon(buddy);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Buddy::Icon");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_contact); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_contact)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_contact", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__BuddyList__Contact	RETVAL;

	RETVAL = purple_buddy_get_contact(buddy);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::BuddyList::Contact");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_presence); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_presence)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_presence", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	Purple__Presence	RETVAL;

	RETVAL = purple_buddy_get_presence(buddy);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Presence");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_alias_only); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_alias_only)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_alias_only", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_buddy_get_alias_only(buddy);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_contact_alias); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_contact_alias)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_contact_alias", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_buddy_get_contact_alias(buddy);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_local_alias); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_local_alias)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_local_alias", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_buddy_get_local_alias(buddy);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__BuddyList__Buddy_get_alias); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__BuddyList__Buddy_get_alias)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::BuddyList::Buddy::get_alias", "buddy");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__BuddyList__Buddy	buddy = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_buddy_get_alias(buddy);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__BuddyList); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__BuddyList)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::get_blist", XS_Purple_get_blist, file, "");
        newXSproto("Purple::set_blist", XS_Purple_set_blist, file, "$");
        newXSproto("Purple::Find::buddy", XS_Purple__Find_buddy, file, "$$");
        newXSproto("Purple::Find::buddies", XS_Purple__Find_buddies, file, "$$");
        newXSproto("Purple::Find::group", XS_Purple__Find_group, file, "$");
        newXSproto("Purple::Find::group_on_account", XS_Purple__Find_group_on_account, file, "$$");
        newXSproto("Purple::BuddyList::Contact::new", XS_Purple__BuddyList__Contact_new, file, "");
        newXSproto("Purple::BuddyList::Contact::get_priority_buddy", XS_Purple__BuddyList__Contact_get_priority_buddy, file, "$");
        newXSproto("Purple::BuddyList::Contact::set_alias", XS_Purple__BuddyList__Contact_set_alias, file, "$$");
        newXSproto("Purple::BuddyList::Contact::get_alias", XS_Purple__BuddyList__Contact_get_alias, file, "$");
        newXSproto("Purple::BuddyList::Contact::on_account", XS_Purple__BuddyList__Contact_on_account, file, "$$");
        newXSproto("Purple::BuddyList::Contact::invalidate_priority_buddy", XS_Purple__BuddyList__Contact_invalidate_priority_buddy, file, "$");
        newXSproto("Purple::BuddyList::Group::new", XS_Purple__BuddyList__Group_new, file, "$");
        newXSproto("Purple::BuddyList::Group::get_accounts", XS_Purple__BuddyList__Group_get_accounts, file, "$");
        newXSproto("Purple::BuddyList::Group::on_account", XS_Purple__BuddyList__Group_on_account, file, "$$");
        newXSproto("Purple::BuddyList::Group::get_name", XS_Purple__BuddyList__Group_get_name, file, "$");
        newXSproto("Purple::BuddyList::add_contact", XS_Purple__BuddyList_add_contact, file, "$$$");
        newXSproto("Purple::BuddyList::merge_contact", XS_Purple__BuddyList_merge_contact, file, "$$");
        newXSproto("Purple::BuddyList::add_group", XS_Purple__BuddyList_add_group, file, "$$");
        newXSproto("Purple::BuddyList::add_buddy", XS_Purple__BuddyList_add_buddy, file, "$$$$");
        newXSproto("Purple::BuddyList::remove_buddy", XS_Purple__BuddyList_remove_buddy, file, "$");
        newXSproto("Purple::BuddyList::remove_contact", XS_Purple__BuddyList_remove_contact, file, "$");
        newXSproto("Purple::BuddyList::remove_chat", XS_Purple__BuddyList_remove_chat, file, "$");
        newXSproto("Purple::BuddyList::remove_group", XS_Purple__BuddyList_remove_group, file, "$");
        newXSproto("Purple::BuddyList::find_chat", XS_Purple__BuddyList_find_chat, file, "$$");
        newXSproto("Purple::BuddyList::add_chat", XS_Purple__BuddyList_add_chat, file, "$$$");
        newXSproto("Purple::BuddyList::new", XS_Purple__BuddyList_new, file, "");
        newXSproto("Purple::BuddyList::show", XS_Purple__BuddyList_show, file, "");
        newXSproto("Purple::BuddyList::destroy", XS_Purple__BuddyList_destroy, file, "");
        newXSproto("Purple::BuddyList::set_visible", XS_Purple__BuddyList_set_visible, file, "$");
        newXSproto("Purple::BuddyList::update_buddy_status", XS_Purple__BuddyList_update_buddy_status, file, "$$");
        newXSproto("Purple::BuddyList::update_buddy_icon", XS_Purple__BuddyList_update_buddy_icon, file, "$");
        newXSproto("Purple::BuddyList::rename_buddy", XS_Purple__BuddyList_rename_buddy, file, "$$");
        newXSproto("Purple::BuddyList::alias_buddy", XS_Purple__BuddyList_alias_buddy, file, "$$");
        newXSproto("Purple::BuddyList::server_alias_buddy", XS_Purple__BuddyList_server_alias_buddy, file, "$$");
        newXSproto("Purple::BuddyList::alias_chat", XS_Purple__BuddyList_alias_chat, file, "$$");
        newXSproto("Purple::BuddyList::rename_group", XS_Purple__BuddyList_rename_group, file, "$$");
        newXSproto("Purple::BuddyList::add_account", XS_Purple__BuddyList_add_account, file, "$");
        newXSproto("Purple::BuddyList::remove_account", XS_Purple__BuddyList_remove_account, file, "$");
        newXSproto("Purple::BuddyList::get_group_size", XS_Purple__BuddyList_get_group_size, file, "$$");
        newXSproto("Purple::BuddyList::get_group_online_count", XS_Purple__BuddyList_get_group_online_count, file, "$");
        newXSproto("Purple::BuddyList::load", XS_Purple__BuddyList_load, file, "");
        newXSproto("Purple::BuddyList::schedule_save", XS_Purple__BuddyList_schedule_save, file, "");
        newXSproto("Purple::BuddyList::request_add_group", XS_Purple__BuddyList_request_add_group, file, "");
        newXSproto("Purple::BuddyList::get_handle", XS_Purple__BuddyList_get_handle, file, "");
        newXSproto("Purple::BuddyList::get_root", XS_Purple__BuddyList_get_root, file, "");
        newXSproto("Purple::BuddyList::Node::get_extended_menu", XS_Purple__BuddyList__Node_get_extended_menu, file, "$");
        newXSproto("Purple::BuddyList::Node::set_bool", XS_Purple__BuddyList__Node_set_bool, file, "$$$");
        newXSproto("Purple::BuddyList::Node::get_bool", XS_Purple__BuddyList__Node_get_bool, file, "$$");
        newXSproto("Purple::BuddyList::Node::set_int", XS_Purple__BuddyList__Node_set_int, file, "$$$");
        newXSproto("Purple::BuddyList::Node::get_int", XS_Purple__BuddyList__Node_get_int, file, "$$");
        newXSproto("Purple::BuddyList::Node::get_string", XS_Purple__BuddyList__Node_get_string, file, "$$");
        newXSproto("Purple::BuddyList::Node::remove_setting", XS_Purple__BuddyList__Node_remove_setting, file, "$$");
        newXSproto("Purple::BuddyList::Node::set_flags", XS_Purple__BuddyList__Node_set_flags, file, "$$");
        newXSproto("Purple::BuddyList::Node::get_flags", XS_Purple__BuddyList__Node_get_flags, file, "$");
        newXSproto("Purple::BuddyList::Node::get_type", XS_Purple__BuddyList__Node_get_type, file, "$");
        newXSproto("Purple::BuddyList::Node::next", XS_Purple__BuddyList__Node_next, file, "$$");
        newXSproto("Purple::BuddyList::Chat::get_group", XS_Purple__BuddyList__Chat_get_group, file, "$");
        newXSproto("Purple::BuddyList::Chat::get_name", XS_Purple__BuddyList__Chat_get_name, file, "$");
        newXSproto("Purple::BuddyList::Chat::new", XS_Purple__BuddyList__Chat_new, file, "$$$");
        newXSproto("Purple::BuddyList::Buddy::new", XS_Purple__BuddyList__Buddy_new, file, "$$$");
        newXSproto("Purple::BuddyList::Buddy::get_server_alias", XS_Purple__BuddyList__Buddy_get_server_alias, file, "$");
        newXSproto("Purple::BuddyList::Buddy::set_icon", XS_Purple__BuddyList__Buddy_set_icon, file, "$$");
        newXSproto("Purple::BuddyList::Buddy::get_account", XS_Purple__BuddyList__Buddy_get_account, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_group", XS_Purple__BuddyList__Buddy_get_group, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_name", XS_Purple__BuddyList__Buddy_get_name, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_icon", XS_Purple__BuddyList__Buddy_get_icon, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_contact", XS_Purple__BuddyList__Buddy_get_contact, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_presence", XS_Purple__BuddyList__Buddy_get_presence, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_alias_only", XS_Purple__BuddyList__Buddy_get_alias_only, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_contact_alias", XS_Purple__BuddyList__Buddy_get_contact_alias, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_local_alias", XS_Purple__BuddyList__Buddy_get_local_alias, file, "$");
        newXSproto("Purple::BuddyList::Buddy::get_alias", XS_Purple__BuddyList__Buddy_get_alias, file, "$");

    /* Initialisation Section */

#line 9 "BuddyList.xs"
{
	HV *stash = gv_stashpv("Purple::BuddyList::Node", 1);

	static const constiv *civ, const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_BLIST_##name##_NODE}
		const_iv(GROUP),
		const_iv(CONTACT),
		const_iv(BUDDY),
		const_iv(CHAT),
		const_iv(OTHER),
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_BLIST_NODE_FLAG_##name}
		const_iv(NO_SAVE),
	};

	for (civ = const_iv + sizeof(const_iv) / sizeof(const_iv[0]); civ-- > const_iv; )
		newCONSTSUB(stash, (char *)civ->name, newSViv(civ->iv));
}

#line 1809 "BuddyList.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

