/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Core.xs. Do not edit this file, edit Core.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Core.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Core.c"

XS(XS_Purple__Core_quit_cb); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Core_quit_cb)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Core::quit_cb", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	gboolean	RETVAL;
#line 9 "Core.xs"
	/* The argument to purple_core_quit_cb is not used,
	 * so there's little point in requiring it on the
	 * Perl side. */
	RETVAL = purple_core_quit_cb(NULL);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
#line 41 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Core_get_version); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Core_get_version)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Core::get_version", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_core_get_version();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Core_get_ui); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Core_get_ui)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Core::get_ui", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_core_get_ui();
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Core); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Core)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Core::quit_cb", XS_Purple__Core_quit_cb, file, "");
        newXSproto("Purple::Core::get_version", XS_Purple__Core_get_version, file, "");
        newXSproto("Purple::Core::get_ui", XS_Purple__Core_get_ui, file, "");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

