/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Pounce.xs. Do not edit this file, edit Pounce.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Pounce.xs"
#include "module.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 17 "Pounce.c"

XS(XS_Purple__Pounce_action_register); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_action_register)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::action_register", "pounce, name");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	const char *	name = (const char *)SvPV_nolen(ST(1));

	purple_pounce_action_register(pounce, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounce_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_destroy)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::destroy", "pounce");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));

	purple_pounce_destroy(pounce);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounce_destroy_all_by_account); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_destroy_all_by_account)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::destroy_all_by_account", "account");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Account	account = purple_perl_ref_object(ST(0));

	purple_pounce_destroy_all_by_account(account);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounce_get_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_get_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::get_data", "pounce");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	void *	RETVAL;
	dXSTARG;

	RETVAL = purple_pounce_get_data(pounce);
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Purple__Pounce_get_events); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_get_events)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::get_events", "pounce");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	Purple__PounceEvent	RETVAL;
	dXSTARG;

	RETVAL = purple_pounce_get_events(pounce);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Purple__Pounce_get_pouncee); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_get_pouncee)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::get_pouncee", "pounce");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	const char *	RETVAL;
	dXSTARG;

	RETVAL = purple_pounce_get_pouncee(pounce);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Purple__Pounce_get_pouncer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_get_pouncer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::get_pouncer", "pounce");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	Purple__Account	RETVAL;

	RETVAL = purple_pounce_get_pouncer(pounce);
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Account");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Pounce_get_save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_get_save)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::get_save", "pounce");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	gboolean	RETVAL;

	RETVAL = purple_pounce_get_save(pounce);
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Pounce_set_data); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_set_data)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::set_data", "pounce, data");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	void *	data = INT2PTR(void *,SvIV(ST(1)));

	purple_pounce_set_data(pounce, data);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounce_set_events); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_set_events)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::set_events", "pounce, events");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	Purple__PounceEvent	events = (Purple__PounceEvent)SvIV(ST(1));

	purple_pounce_set_events(pounce, events);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounce_set_pouncee); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_set_pouncee)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::set_pouncee", "pounce, pouncee");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	const char *	pouncee = (const char *)SvPV_nolen(ST(1));

	purple_pounce_set_pouncee(pounce, pouncee);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounce_set_pouncer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_set_pouncer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::set_pouncer", "pounce, pouncer");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	Purple__Account	pouncer = purple_perl_ref_object(ST(1));

	purple_pounce_set_pouncer(pounce, pouncer);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounce_set_save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounce_set_save)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounce::set_save", "pounce, save");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Pounce	pounce = purple_perl_ref_object(ST(0));
	gboolean	save = (bool)SvTRUE(ST(1));

	purple_pounce_set_save(pounce, save);
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Pounces_get_all); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounces_get_all)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounces::get_all", "");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 103 "Pounce.xs"
	GList *l;
#line 317 "Pounce.c"
#line 105 "Pounce.xs"
	for (l = purple_pounces_get_all(); l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Pounce")));
	}
#line 322 "Pounce.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Pounces_get_all_for_ui); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounces_get_all_for_ui)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounces::get_all_for_ui", "ui");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	const char *	ui = (const char *)SvPV_nolen(ST(0));
#line 113 "Pounce.xs"
	GList *l, *ll;
#line 346 "Pounce.c"
#line 115 "Pounce.xs"
	ll = purple_pounces_get_all_for_ui(ui);
	for (l = ll; l != NULL; l = l->next) {
		XPUSHs(sv_2mortal(purple_perl_bless_object(l->data, "Purple::Pounce")));
	}
	g_list_free(ll);
#line 353 "Pounce.c"
	PUTBACK;
	return;
    }
}


XS(XS_Purple__Pounces_get_handle); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounces_get_handle)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounces::get_handle", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	RETVAL;

	RETVAL = purple_pounces_get_handle();
	ST(0) = purple_perl_bless_object(RETVAL, "Purple::Handle");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Pounces_load); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounces_load)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounces::load", "");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	gboolean	RETVAL;

	RETVAL = purple_pounces_load();
	ST(0) = boolSV(RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Purple__Pounces_unregister_handler); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Pounces_unregister_handler)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Pounces::unregister_handler", "ui");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	const char *	ui = (const char *)SvPV_nolen(ST(0));

	purple_pounces_unregister_handler(ui);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Pounce); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Pounce)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Pounce::action_register", XS_Purple__Pounce_action_register, file, "$$");
        newXSproto("Purple::Pounce::destroy", XS_Purple__Pounce_destroy, file, "$");
        newXSproto("Purple::Pounce::destroy_all_by_account", XS_Purple__Pounce_destroy_all_by_account, file, "$");
        newXSproto("Purple::Pounce::get_data", XS_Purple__Pounce_get_data, file, "$");
        newXSproto("Purple::Pounce::get_events", XS_Purple__Pounce_get_events, file, "$");
        newXSproto("Purple::Pounce::get_pouncee", XS_Purple__Pounce_get_pouncee, file, "$");
        newXSproto("Purple::Pounce::get_pouncer", XS_Purple__Pounce_get_pouncer, file, "$");
        newXSproto("Purple::Pounce::get_save", XS_Purple__Pounce_get_save, file, "$");
        newXSproto("Purple::Pounce::set_data", XS_Purple__Pounce_set_data, file, "$$");
        newXSproto("Purple::Pounce::set_events", XS_Purple__Pounce_set_events, file, "$$");
        newXSproto("Purple::Pounce::set_pouncee", XS_Purple__Pounce_set_pouncee, file, "$$");
        newXSproto("Purple::Pounce::set_pouncer", XS_Purple__Pounce_set_pouncer, file, "$$");
        newXSproto("Purple::Pounce::set_save", XS_Purple__Pounce_set_save, file, "$$");
        newXSproto("Purple::Pounces::get_all", XS_Purple__Pounces_get_all, file, "");
        newXSproto("Purple::Pounces::get_all_for_ui", XS_Purple__Pounces_get_all_for_ui, file, "$");
        newXSproto("Purple::Pounces::get_handle", XS_Purple__Pounces_get_handle, file, "");
        newXSproto("Purple::Pounces::load", XS_Purple__Pounces_load, file, "");
        newXSproto("Purple::Pounces::unregister_handler", XS_Purple__Pounces_unregister_handler, file, "$");

    /* Initialisation Section */

#line 7 "Pounce.xs"
{
	HV *event_stash = gv_stashpv("Purple::Pounce::Event", 1);
	HV *option_stash = gv_stashpv("Purple::Pounce::Option", 1);

	static const constiv *civ, event_const_iv[] = {
#define const_iv(name) {#name, (IV)PURPLE_POUNCE_##name}
		const_iv(NONE),
		const_iv(SIGNON),
		const_iv(SIGNOFF),
		const_iv(AWAY),
		const_iv(AWAY_RETURN),
		const_iv(IDLE),
		const_iv(IDLE_RETURN),
		const_iv(TYPING),
		const_iv(TYPED),
		const_iv(TYPING_STOPPED),
		const_iv(MESSAGE_RECEIVED),
	};
	static const constiv option_const_iv[] = {
#undef const_iv
#define const_iv(name) {#name, (IV)PURPLE_POUNCE_OPTION_##name}
		const_iv(NONE),
		const_iv(AWAY),
	};

	for (civ = event_const_iv + sizeof(event_const_iv) / sizeof(event_const_iv[0]); civ-- > event_const_iv; )
		newCONSTSUB(event_stash, (char *)civ->name, newSViv(civ->iv));

	for (civ = option_const_iv + sizeof(option_const_iv) / sizeof(option_const_iv[0]); civ-- > option_const_iv; )
		newCONSTSUB(option_stash, (char *)civ->name, newSViv(civ->iv));
}

#line 495 "Pounce.c"

    /* End of Initialisation Section */

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

