/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Signal.xs. Do not edit this file, edit Signal.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Signal.xs"
#include "module.h"
#include "../perl-handlers.h"

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 18 "Signal.c"

XS(XS_Purple__Signal_connect_priority); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Signal_connect_priority)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 5 || items > 6)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Signal::connect_priority", "instance, signal, plugin, callback, priority, data = 0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	instance = purple_perl_ref_object(ST(0));
	const char *	signal = (const char *)SvPV_nolen(ST(1));
	Purple__Plugin	plugin = purple_perl_ref_object(ST(2));
	SV *	callback = ST(3);
	int	priority = (int)SvIV(ST(4));
	SV *	data;

	if (items < 6)
	    data = 0;
	else {
	    data = ST(5);
	}
#line 16 "Signal.xs"
	purple_perl_signal_connect(plugin, instance, signal, callback, data, priority);
#line 46 "Signal.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Signal_connect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Signal_connect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 4 || items > 5)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Signal::connect", "instance, signal, plugin, callback, data = 0");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	instance = purple_perl_ref_object(ST(0));
	const char *	signal = (const char *)SvPV_nolen(ST(1));
	Purple__Plugin	plugin = purple_perl_ref_object(ST(2));
	SV *	callback = ST(3);
	SV *	data;

	if (items < 5)
	    data = 0;
	else {
	    data = ST(4);
	}
#line 26 "Signal.xs"
	purple_perl_signal_connect(plugin, instance, signal, callback, data, PURPLE_SIGNAL_PRIORITY_DEFAULT);
#line 77 "Signal.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Purple__Signal_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Purple__Signal_disconnect)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Purple::Signal::disconnect", "instance, signal, plugin");
    PERL_UNUSED_VAR(cv); /* -W */
    {
	Purple__Handle	instance = purple_perl_ref_object(ST(0));
	const char *	signal = (const char *)SvPV_nolen(ST(1));
	Purple__Plugin	plugin = purple_perl_ref_object(ST(2));
#line 34 "Signal.xs"
	purple_perl_signal_disconnect(plugin, instance, signal);
#line 100 "Signal.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Purple__Signal); /* prototype to pass -Wmissing-prototypes */
XS(boot_Purple__Signal)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Purple::Signal::connect_priority", XS_Purple__Signal_connect_priority, file, "$$$$$;$");
        newXSproto("Purple::Signal::connect", XS_Purple__Signal_connect, file, "$$$$;$");
        newXSproto("Purple::Signal::disconnect", XS_Purple__Signal_disconnect, file, "$$$");
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

